services:
  database:
    image: postgres
    restart: always
    environment:
      PGDATA: /data/pgdata
      POSTGRES_DB: gatekeeper
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/data/pgdata
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "gatekeeper" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/gatekeeper
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_BASE64: ${JWT_SECRET_BASE64}
    depends_on:
      database:
        condition: service_healthy

volumes:
  pgdata: